cassandra {
  host = "cassandra"
  keyspace = "market"
  username = "cassandra"
  password = "cassandra"

  tables {
    trades = "trades"
    aggregates = "aggregates"
  }
}

kafka {
  server = "kafka"
  port = "9092"

  topics {
    market = "market"
  }

  min_partitions {
    StreamProcessor = "1"
  }
}

spark {
  master = "local[*]"

  appName {
    StreamProcessor = "StreamProcessorApp"
  }

  max_offsets_per_trigger {
    StreamProcessor = "100"
  }

  shuffle_partitions {
    StreamProcessor = "2"
  }

  deprecated_offsets {
    StreamProcessor = "false"
  }
}

schemas {
  trades = "/schemas/trades.avsc"
}